//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTXClassLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTXClassLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTXDataTypeUID,PTXDefaultOther,PTXDataTypeName,PTXDataTypeT1,T1AllowNullable,T1Min,T1Max,T1List,T1Default,PTXDataTypeT2,T2AllowNullable,T2Min,T2Max,T2List,T2Default
        ///asd,,,,,,,,,,,,BoolList,,
        ///.
        /// </summary>
        internal static string PTXDataTypesTable {
            get {
                return ResourceManager.GetString("PTXDataTypesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        /// {
        ///   &quot;PTXDataTypeUID&quot;: &quot;memTitle&quot;,
        ///   &quot;PTXDefaultOther&quot;: &quot;Default&quot;,
        ///   &quot;PTXDataTypeDescription&quot;: &quot;1. memTitle: Represents a member&apos;s title, such as Mr, Ms, Mrs, Miss, Dr, etc.&quot;,
        ///   &quot;PTXDataTypeName&quot;: &quot;memTitle&quot;,
        ///   &quot;PTXDataTypeT1&quot;: &quot;string&quot;,
        ///   &quot;T1Allownullable&quot;: true,
        ///   &quot;T1Min&quot;: &quot;#NA&quot;,
        ///   &quot;T1Max&quot;: &quot;#NA&quot;,
        ///   &quot;T1List&quot;: [&quot;&quot;,&quot;Mr&quot;,&quot;Ms&quot;,&quot;Mrs&quot;,&quot;Miss&quot;,&quot;Dr&quot;,&quot;Prof&quot;,&quot;Rev&quot;,&quot;Sir&quot;,&quot;Madam&quot;,&quot;Lord&quot;,&quot;Lady&quot;,&quot;Mx&quot;,&quot;Monsieur&quot;,&quot;Mademoiselle&quot;,&quot;Count&quot;,&quot;Countess&quot;,&quot;Baron&quot;,&quot;Baroness&quot;,&quot;Duke&quot;,&quot;Duchess&quot;],
        ///   &quot;T1Default&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PTXDataTypesTableJson {
            get {
                return ResourceManager.GetString("PTXDataTypesTableJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTXCalcName,DataTypeName,PensionDataType,PTXClassName,Description,KnownNames[List]
        ///Pre88Post78GMPBenDOL,System.Double,Member,Benefits,Pre 88 Bens at DOL,Pre88 GMP at DOL,,Pre88GMPPenDOL,Pre88GMPBenDOL,
        ///Pre90Post88GMPBenDOL,Double,Member,Benefits,,Pre90 GMP at DOL,,,,
        ///Pre97Post90GMPBenDOL,Double,Member,Benefits,,Post 90 GMP at DOL,,,,
        ///Pre85Post78XSBenDOL,Double,Member,Benefits,,Pre85 XS at DOL,,,,
        ///Pre88Post85XSBenDOL,Double,Member,Benefits,,Pre88 XS At DOL,,,,
        ///Pre90Post88XSBenDOL,Double,Member,Benefits [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PTXFieldDictionaryAndMapTable {
            get {
                return ResourceManager.GetString("PTXFieldDictionaryAndMapTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        /// {
        ///   &quot;PTXCalcName&quot;: &quot;SourceOfKnownName&quot;,
        ///   &quot;PTXDataTypeName&quot;: &quot;#NA&quot;,
        ///   &quot;PensionDataType&quot;: &quot;#NA&quot;,
        ///   &quot;PTXClassName&quot;: &quot;#NA&quot;,
        ///   &quot;Description&quot;: &quot;Source of data&quot;,
        ///   &quot;KnownNames&quot;: &quot;[General\&quot;,\&quot;General\&quot;,\&quot;General\&quot;,\&quot;General\&quot;,\&quot;Compendia\&quot;,\&quot;Client XYZ]&quot;
        /// },
        /// {
        ///   &quot;PTXCalcName&quot;: &quot;memPre88Post78GMPBenDOL&quot;,
        ///   &quot;PTXDataTypeName&quot;: &quot;double&quot;,
        ///   &quot;PensionDataType&quot;: &quot;Member&quot;,
        ///   &quot;PTXClassName&quot;: &quot;To Be completed&quot;,
        ///   &quot;Description&quot;: &quot;To Be completed&quot;,
        ///   &quot;KnownNames&quot;: &quot;[memPre88Post78GMPBenDOL\&quot;,\&quot;P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PTXFieldDictionaryAndMapTableJson {
            get {
                return ResourceManager.GetString("PTXFieldDictionaryAndMapTableJson", resourceCulture);
            }
        }
    }
}
